### ISSUE TITLE
Typo on README

### ISSUE THREAD

**Issue by marimeireles** [shreyanshk/flask-firehose#1]
Hi!
I think there is a typo in your README.rst file. In the [Pushing resources](https://github.com/shreyanshk/flask-firehose/blob/master/README.rst#pushing-resources) section it's written that we should use something like `push('/static/css/main.css', as='style', rel='preload')` to push files, but the `as` will cause python to crash.
Going through the repo I found this example:
https://github.com/shreyanshk/flask-firehose/blob/3d71e6ce39c2d9a4566a018ec9443dcc3e06dd57/testapp/server.py#L22
Where you're not using `as`.

Testing on my computer I found that not using `as` like you did in your tests allows python to run.

But when I test on my local server I get the following error:

`<link rel=preload> must have a valid `as` value`

Any idea of what might be happening here?

Thanks a lot!

**Comment by marimeireles** [comment]
I think I figured out the problem.
I'm currently using python 2 and as is a reserved word.
Doing something like:
```
    push('/css/dist/webcompat.min.css', **{
        'as': 'style',
        'rel': 'preload'
    })
```
Fixes the problem.

**Comment by shreyanshk** [comment]
Hi @marimeireles,
Thank you for identifying the error.
Please consider making a contribution to this repository. You could update the documentation and then open a pull request.

Thank you.

**Comment by shreyanshk** [comment]
Thank you for your contribution.
